apiVersion: apps/v1
kind: Deployment
metadata:
  name: target-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: target-app
  template:
    metadata:
      labels:
        app: target-app
    spec:
      containers:
      - name: target-app
        image: python:3.9-slim
        imagePullPolicy: IfNotPresent
        command: ['/bin/sh', '-c']
        args: ['pip install Flask && python /app/main.py']
        volumeMounts:
        - name: app-code
          mountPath: /app
      volumes:
      - name: app-code
        configMap:
          name: target-app-code
